### ISSUE TITLE
Serial plotter not plotting

### ISSUE THREAD

**Issue by AndKe** [arduino/arduino-serial-plotter-webapp#33]
### Describe the problem

lines like these are not plotted:

Temperature: 23.64, Humidity: 43.89
Temperature: 23.64, Humidity: 43.91
Temperature: 23.64, Humidity: 43.92

![Screenshot from 2023-08-31 10-25-06](https://github.com/arduino/arduino-ide/assets/1468842/53c5e469-2e95-4653-94cc-46cea9dc93ec)

### To reproduce

push strings above.

### Expected behavior

plot, accoring to https://docs.arduino.cc/software/ide-v2/tutorials/ide-v2-serial-plotter this should work?

### Arduino IDE version

2.2.0

### Operating system

Linux

### Operating system version

Ubuntu 23.04

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the problem still occurs when using the latest [nightly build](https://www.arduino.cc/en/software#nightly-builds)
- [X] My report contains all necessary details

**Comment by per1234** [comment]
Hi @AndKe. Since the space is one of the data delimiters recognized by the Serial Plotter, it is mandatory that you not insert a space between the colon and the value.

So you must change this line of your sketch:

```cpp
Serial.print("Temperature: ");
```
to this:
```cpp
Serial.print("Temperature:");
```

and change this line of your sketch:

```cpp
Serial.print(", Humidity: ");
```
to this:
```cpp
Serial.print(", Humidity:");
```

If you check the tutorial closely, you'll see the code there does meet this requirement.

**Comment by AndKe** [comment]
@per1234 thank you. my bad, maybe a short example/requirement text box/help box would be nice to have in the plotter window.
